import { Exercise } from '@/types';

export const EXERCISES: Omit<Exercise, 'id'>[] = [
  {
    slug: 'chin-tuck',
    name: 'Chin Tuck',
    category: 'corrective',
    muscle_groups: ['deep cervical flexors', 'neck'],
    equipment: ['none'],
    difficulty: 'beginner',
    posture_tags: ['forward_head'],
    sets_default: 3,
    reps_default: '10',
    rest_seconds: 30,
    video_url: null,
    thumbnail_url: null,
    coaching_cue: 'Glide your chin straight back — like you\'re making a double chin — without tilting your head.',
    why_it_helps: 'Reactivates the deep neck flexors that switch off when your head drifts forward, pulling your head back over your shoulders.',
  },
  {
    slug: 'deep-neck-flexor-activation',
    name: 'Deep Neck Flexor Activation',
    category: 'corrective',
    muscle_groups: ['deep cervical flexors'],
    equipment: ['none'],
    difficulty: 'beginner',
    posture_tags: ['forward_head'],
    sets_default: 3,
    reps_default: '10',
    rest_seconds: 30,
    video_url: null,
    thumbnail_url: null,
    coaching_cue: 'Lie on your back, nod your chin gently toward your chest — only 5–10°. Hold 5 seconds.',
    why_it_helps: 'Directly strengthens the small muscles at the front of your neck that control head position. Essential for correcting forward head posture.',
  },
  {
    slug: 'thoracic-extension',
    name: 'Thoracic Extension Over Foam Roller',
    category: 'mobility',
    muscle_groups: ['thoracic spine', 'erector spinae'],
    equipment: ['home'],
    difficulty: 'beginner',
    posture_tags: ['forward_head', 'kyphosis', 'rounded_shoulders'],
    sets_default: 2,
    reps_default: '8',
    rest_seconds: 45,
    video_url: null,
    thumbnail_url: null,
    coaching_cue: 'Place the roller across your mid-back. Support your head, extend back over the roller slowly. Move it up or down your spine.',
    why_it_helps: 'Opens the thoracic spine which is often stiff from sitting. Restoring extension here naturally pulls your shoulders back and head upright.',
  },
  {
    slug: 'face-pull',
    name: 'Face Pull',
    category: 'corrective',
    muscle_groups: ['rear deltoids', 'rotator cuff', 'rhomboids'],
    equipment: ['home', 'gym'],
    difficulty: 'beginner',
    posture_tags: ['rounded_shoulders'],
    sets_default: 3,
    reps_default: '15',
    rest_seconds: 45,
    video_url: null,
    thumbnail_url: null,
    coaching_cue: 'Pull the band to your face, elbows flaring out and back. Squeeze your shoulder blades together at the end of each rep.',
    why_it_helps: 'Strengthens the rear deltoids and external rotators that are chronically weak in people with rounded shoulders, pulling them back into alignment.',
  },
  {
    slug: 'wall-angel',
    name: 'Wall Angel',
    category: 'corrective',
    muscle_groups: ['lower trapezius', 'serratus anterior', 'thoracic spine'],
    equipment: ['none'],
    difficulty: 'beginner',
    posture_tags: ['rounded_shoulders', 'kyphosis'],
    sets_default: 3,
    reps_default: '10',
    rest_seconds: 45,
    video_url: null,
    thumbnail_url: null,
    coaching_cue: 'Stand with your back, head, and arms flat against a wall. Slide arms overhead while keeping everything in contact with the wall.',
    why_it_helps: 'Trains your scapulae to move correctly while opening your chest and strengthening the postural muscles of your upper back.',
  },
  {
    slug: 'band-pull-apart',
    name: 'Band Pull-Apart',
    category: 'corrective',
    muscle_groups: ['rear deltoids', 'rhomboids', 'middle trapezius'],
    equipment: ['home'],
    difficulty: 'beginner',
    posture_tags: ['rounded_shoulders'],
    sets_default: 3,
    reps_default: '15',
    rest_seconds: 30,
    video_url: null,
    thumbnail_url: null,
    coaching_cue: 'Hold a band in front at chest height, arms straight. Pull it apart until fully stretched, squeezing shoulder blades together.',
    why_it_helps: 'Targets the horizontal pulling muscles that balance out the chest — the most overlooked muscle group in people who sit at desks.',
  },
  {
    slug: 'doorway-chest-stretch',
    name: 'Doorway Chest Stretch',
    category: 'mobility',
    muscle_groups: ['pectoralis major', 'pectoralis minor', 'anterior deltoid'],
    equipment: ['none'],
    difficulty: 'beginner',
    posture_tags: ['rounded_shoulders', 'forward_head'],
    sets_default: 2,
    reps_default: '30 sec',
    rest_seconds: 30,
    video_url: null,
    thumbnail_url: null,
    coaching_cue: 'Stand in a doorway, forearms on the frame. Step forward until you feel a stretch across your chest. Don\'t arch your lower back.',
    why_it_helps: 'Stretches the tight chest muscles that pull your shoulders forward. Short pecs are one of the main causes of rounded shoulders.',
  },
  {
    slug: 'seated-row',
    name: 'Seated Cable Row',
    category: 'strength',
    muscle_groups: ['rhomboids', 'middle trapezius', 'biceps', 'lats'],
    equipment: ['gym'],
    difficulty: 'beginner',
    posture_tags: ['rounded_shoulders'],
    sets_default: 3,
    reps_default: '12',
    rest_seconds: 60,
    video_url: null,
    thumbnail_url: null,
    coaching_cue: 'Pull to your lower chest, elbows close to your sides. Hold 1 second at the top. Control the weight back — don\'t let it yank you forward.',
    why_it_helps: 'One of the most effective exercises for building the mid-back strength that holds your shoulders in proper alignment throughout the day.',
  },
  {
    slug: 'upper-trap-stretch',
    name: 'Upper Trapezius Stretch',
    category: 'mobility',
    muscle_groups: ['upper trapezius', 'levator scapulae'],
    equipment: ['none'],
    difficulty: 'beginner',
    posture_tags: ['shoulder_asymmetry'],
    sets_default: 2,
    reps_default: '30 sec each side',
    rest_seconds: 30,
    video_url: null,
    thumbnail_url: null,
    coaching_cue: 'Sit tall. Tilt your ear to your shoulder while gently pulling your head with the opposite hand. Keep the other shoulder down.',
    why_it_helps: 'Releases the chronically tight upper trap that elevates one shoulder higher than the other, causing neck tension and asymmetrical posture.',
  },
  {
    slug: 'single-arm-carry',
    name: 'Single Arm Farmer\'s Carry',
    category: 'strength',
    muscle_groups: ['core', 'obliques', 'trapezius', 'grip'],
    equipment: ['home', 'gym'],
    difficulty: 'intermediate',
    posture_tags: ['shoulder_asymmetry'],
    sets_default: 3,
    reps_default: '30 sec each side',
    rest_seconds: 60,
    video_url: null,
    thumbnail_url: null,
    coaching_cue: 'Hold a weight in one hand, stand tall, and walk. Resist the urge to lean — your core should work to keep you upright.',
    why_it_helps: 'Forces your core to stabilise against lateral load, correcting muscle imbalances that cause one shoulder to sit higher than the other.',
  },
  {
    slug: 'side-lying-external-rotation',
    name: 'Side-Lying External Rotation',
    category: 'corrective',
    muscle_groups: ['infraspinatus', 'teres minor', 'rotator cuff'],
    equipment: ['none', 'home'],
    difficulty: 'beginner',
    posture_tags: ['shoulder_asymmetry'],
    sets_default: 3,
    reps_default: '12 each side',
    rest_seconds: 45,
    video_url: null,
    thumbnail_url: null,
    coaching_cue: 'Lie on your side, elbow bent at 90°. Rotate your forearm up toward the ceiling slowly. Don\'t let your elbow move from your side.',
    why_it_helps: 'Directly targets the small rotator cuff muscles that control shoulder positioning — often weak on one side, creating visible asymmetry.',
  },
  {
    slug: 'hip-flexor-stretch',
    name: 'Kneeling Hip Flexor Stretch',
    category: 'mobility',
    muscle_groups: ['iliopsoas', 'rectus femoris', 'hip flexors'],
    equipment: ['none'],
    difficulty: 'beginner',
    posture_tags: ['anterior_pelvic_tilt'],
    sets_default: 2,
    reps_default: '45 sec each side',
    rest_seconds: 30,
    video_url: null,
    thumbnail_url: null,
    coaching_cue: 'Kneel on one knee. Squeeze your back glute, tuck your pelvis under, then shift forward until you feel a stretch in your front hip.',
    why_it_helps: 'Lengthens shortened hip flexors that pull the front of your pelvis down into an anterior tilt, causing lower back discomfort and a protruding belly.',
  },
  {
    slug: 'glute-bridge',
    name: 'Glute Bridge',
    category: 'corrective',
    muscle_groups: ['gluteus maximus', 'hamstrings', 'core'],
    equipment: ['none'],
    difficulty: 'beginner',
    posture_tags: ['anterior_pelvic_tilt', 'knee_valgus'],
    sets_default: 3,
    reps_default: '15',
    rest_seconds: 45,
    video_url: null,
    thumbnail_url: null,
    coaching_cue: 'Lie on your back, feet flat. Drive through your heels and squeeze your glutes hard at the top. Hold 2 seconds. Don\'t let your lower back arch.',
    why_it_helps: 'Activates weak glutes that fail to control your pelvis. Strong glutes are the primary antagonist to tight hip flexors — the main driver of pelvic tilt.',
  },
  {
    slug: 'dead-bug',
    name: 'Dead Bug',
    category: 'corrective',
    muscle_groups: ['deep core', 'transverse abdominis', 'multifidus'],
    equipment: ['none'],
    difficulty: 'beginner',
    posture_tags: ['anterior_pelvic_tilt'],
    sets_default: 3,
    reps_default: '8 each side',
    rest_seconds: 45,
    video_url: null,
    thumbnail_url: null,
    coaching_cue: 'Lie on your back, arms up, knees at 90°. Lower opposite arm and leg while pressing your lower back into the floor. Switch sides.',
    why_it_helps: 'Trains deep core stability without loading your spine — essential for correcting anterior pelvic tilt and protecting your lower back.',
  },
  {
    slug: 'posterior-pelvic-tilt',
    name: 'Posterior Pelvic Tilt (Lying)',
    category: 'corrective',
    muscle_groups: ['core', 'glutes', 'hip flexors'],
    equipment: ['none'],
    difficulty: 'beginner',
    posture_tags: ['anterior_pelvic_tilt'],
    sets_default: 3,
    reps_default: '15',
    rest_seconds: 30,
    video_url: null,
    thumbnail_url: null,
    coaching_cue: 'Lie on your back, knees bent. Flatten your lower back into the floor by contracting your abs and glutes. Hold 5 seconds.',
    why_it_helps: 'Retrains your pelvis to find neutral position by strengthening the muscles that oppose the anterior tilt pattern.',
  },
  {
    slug: 'prone-cobra',
    name: 'Prone Cobra',
    category: 'corrective',
    muscle_groups: ['lower trapezius', 'rhomboids', 'erector spinae'],
    equipment: ['none'],
    difficulty: 'beginner',
    posture_tags: ['kyphosis'],
    sets_default: 3,
    reps_default: '12',
    rest_seconds: 45,
    video_url: null,
    thumbnail_url: null,
    coaching_cue: 'Lie face down. Lift your chest and rotate your thumbs toward the ceiling, squeezing your shoulder blades together. Look at the floor.',
    why_it_helps: 'Directly strengthens the lower trapezius and thoracic extensors that are lengthened and weak in people with a rounded upper back (kyphosis).',
  },
  {
    slug: 'clamshell',
    name: 'Clamshell',
    category: 'corrective',
    muscle_groups: ['gluteus medius', 'hip external rotators'],
    equipment: ['none', 'home'],
    difficulty: 'beginner',
    posture_tags: ['knee_valgus'],
    sets_default: 3,
    reps_default: '15 each side',
    rest_seconds: 30,
    video_url: null,
    thumbnail_url: null,
    coaching_cue: 'Lie on your side, hips stacked, knees bent at 45°. Open your top knee like a clamshell while keeping your feet together. Don\'t rock your pelvis.',
    why_it_helps: 'Isolates the gluteus medius — the hip muscle that prevents knees from caving inward when you walk, run, or squat.',
  },
  {
    slug: 'side-lying-abduction',
    name: 'Side-Lying Hip Abduction',
    category: 'corrective',
    muscle_groups: ['gluteus medius', 'TFL'],
    equipment: ['none'],
    difficulty: 'beginner',
    posture_tags: ['knee_valgus'],
    sets_default: 3,
    reps_default: '15 each side',
    rest_seconds: 30,
    video_url: null,
    thumbnail_url: null,
    coaching_cue: 'Lie on your side, bottom knee bent for stability. Lift your straight top leg to about 45°. Control it back down slowly.',
    why_it_helps: 'Builds hip abductor strength to keep your knee aligned over your foot — directly correcting knee valgus (knees caving inward).',
  },
  {
    slug: 'goblet-squat',
    name: 'Goblet Squat',
    category: 'strength',
    muscle_groups: ['quadriceps', 'glutes', 'core', 'upper back'],
    equipment: ['home', 'gym'],
    difficulty: 'beginner',
    posture_tags: ['knee_valgus'],
    sets_default: 3,
    reps_default: '12',
    rest_seconds: 60,
    video_url: null,
    thumbnail_url: null,
    coaching_cue: 'Hold a weight at your chest, squat deep. Drive your knees out over your pinky toes. Chest up throughout.',
    why_it_helps: 'The goblet position keeps your torso upright, teaching correct squat mechanics while the movement pattern trains knees to track properly.',
  },
  {
    slug: 'plank',
    name: 'Plank',
    category: 'strength',
    muscle_groups: ['core', 'transverse abdominis', 'shoulders'],
    equipment: ['none'],
    difficulty: 'beginner',
    posture_tags: ['anterior_pelvic_tilt'],
    sets_default: 3,
    reps_default: '30 sec',
    rest_seconds: 45,
    video_url: null,
    thumbnail_url: null,
    coaching_cue: 'Forearms down, body in a straight line from head to heel. Squeeze your glutes. Don\'t let your hips sag or pike up.',
    why_it_helps: 'Builds the anterior core strength needed to hold your pelvis in neutral — reducing the excessive arch that comes with anterior pelvic tilt.',
  },
  {
    slug: 'reverse-lunge',
    name: 'Reverse Lunge',
    category: 'strength',
    muscle_groups: ['quadriceps', 'glutes', 'hamstrings', 'core'],
    equipment: ['none'],
    difficulty: 'beginner',
    posture_tags: ['anterior_pelvic_tilt'],
    sets_default: 3,
    reps_default: '10 each leg',
    rest_seconds: 60,
    video_url: null,
    thumbnail_url: null,
    coaching_cue: 'Step back, lower your back knee toward the floor. Keep your front shin vertical and your torso upright. Drive through your front heel to stand.',
    why_it_helps: 'Strengthens the glutes and quads while stretching the hip flexors of the back leg in every rep — targeting two causes of anterior pelvic tilt simultaneously.',
  },
  {
    slug: 'bodyweight-squat',
    name: 'Bodyweight Squat',
    category: 'strength',
    muscle_groups: ['quadriceps', 'glutes', 'hamstrings'],
    equipment: ['none'],
    difficulty: 'beginner',
    posture_tags: [],
    sets_default: 3,
    reps_default: '15',
    rest_seconds: 45,
    video_url: null,
    thumbnail_url: null,
    coaching_cue: 'Feet shoulder-width apart, toes slightly out. Sit back and down, keeping your chest up and knees tracking over your toes.',
    why_it_helps: 'The fundamental lower body movement pattern. Builds leg strength and reinforces proper knee and hip mechanics used in everyday life.',
  },
  {
    slug: 'push-up',
    name: 'Push-Up',
    category: 'strength',
    muscle_groups: ['pectoralis major', 'triceps', 'anterior deltoid', 'core'],
    equipment: ['none'],
    difficulty: 'beginner',
    posture_tags: [],
    sets_default: 3,
    reps_default: '10',
    rest_seconds: 60,
    video_url: null,
    thumbnail_url: null,
    coaching_cue: 'Hands slightly wider than shoulders. Lower until your chest nearly touches the floor. Keep your body in a rigid plank throughout.',
    why_it_helps: 'Builds pushing strength and core stability. When paired with pulling exercises, maintains the muscle balance that keeps your shoulders healthy.',
  },
  {
    slug: 'diaphragmatic-breathing',
    name: 'Diaphragmatic Breathing',
    category: 'recovery',
    muscle_groups: ['diaphragm', 'deep core'],
    equipment: ['none'],
    difficulty: 'beginner',
    posture_tags: [],
    sets_default: 1,
    reps_default: '10 slow breaths',
    rest_seconds: 0,
    video_url: null,
    thumbnail_url: null,
    coaching_cue: 'Lie down, one hand on chest, one on belly. Breathe in through your nose — only the belly hand should rise. Exhale fully through your mouth.',
    why_it_helps: 'Resets your nervous system, reduces cortisol, and reactivates the diaphragm — the foundation of core stability and proper breathing mechanics.',
  },
  {
    slug: 'walking',
    name: 'Walking (30 min)',
    category: 'cardio',
    muscle_groups: ['full body'],
    equipment: ['none'],
    difficulty: 'beginner',
    posture_tags: [],
    sets_default: 1,
    reps_default: '30 min',
    rest_seconds: 0,
    video_url: null,
    thumbnail_url: null,
    coaching_cue: 'Walk tall — chin back, shoulders relaxed, arms swinging naturally. Aim for a brisk pace where you can hold a conversation but feel warm.',
    why_it_helps: 'The most underrated form of exercise. Improves cardiovascular health, accelerates recovery, and reinforces proper gait patterns.',
  },
];
